DOCS = [
 dict(id='eb-what', topic='Early blight', title='What is early blight',
  text='Early blight is a fungal disease of tomato and potato caused by Alternaria solani. It produces dark brown lesions with concentric rings that look like a target or bullseye, usually surrounded by a yellow halo. It begins on the oldest lowest leaves and moves upward as the season progresses. Severe infection causes defoliation, which exposes fruit to sunscald and reduces yield.',
  tags='early blight alternaria solani target spot concentric rings bullseye lower leaves yellow halo'),
 dict(id='eb-treat', topic='Early blight', title='How to treat early blight',
  text='Remove and destroy affected lower leaves as soon as lesions appear and do not compost them. Apply a protectant fungicide containing chlorothalonil or mancozeb at label rates, repeating every 7 to 10 days during wet weather. Mulch around the base of the plant to stop rain splash carrying spores from soil onto foliage. Water at the soil line early in the day so that leaves dry quickly.',
  tags='early blight treatment fungicide chlorothalonil mancozeb mulch remove leaves spray schedule'),
 dict(id='eb-prevent', topic='Early blight', title='How to prevent early blight',
  text='Rotate tomatoes with non solanaceous crops for two to three seasons because Alternaria survives in crop debris and soil. Space plants generously and stake them so that air moves freely and foliage dries fast. Choose resistant cultivars where they are available. Clear all plant debris at the end of the season.',
  tags='early blight prevention crop rotation spacing staking resistant varieties debris'),
 dict(id='lb-what', topic='Late blight', title='What is late blight',
  text='Late blight is caused by Phytophthora infestans, an oomycete rather than a true fungus. It produces large greasy grey green to brown blotches on leaves, often with white fuzzy growth on the underside in humid conditions. It is the disease responsible for the Irish potato famine. It spreads extremely fast and can destroy an entire crop within days under cool wet conditions.',
  tags='late blight phytophthora infestans oomycete greasy blotches white fuzzy growth potato famine fast spreading'),
 dict(id='lb-treat', topic='Late blight', title='How to treat late blight',
  text='Act immediately because this disease moves faster than any other tomato disease. Remove and destroy infected plants entirely rather than only the affected leaves, and do not leave debris in the field. Apply a protectant fungicide containing mancozeb, chlorothalonil or copper to the remaining healthy plants. Stop overhead irrigation until the outbreak is under control.',
  tags='late blight treatment urgent remove plants mancozeb copper fungicide stop irrigation'),
 dict(id='lb-conditions', topic='Late blight', title='Conditions that favour late blight',
  text='Late blight thrives in cool moist weather, typically between 10 and 24 degrees Celsius with prolonged leaf wetness and relative humidity above 90 percent. Extended cloudy periods, heavy dew and frequent rain create ideal conditions. Monitoring becomes critical during such spells.',
  tags='late blight weather humidity temperature cool wet dew rain conditions favour risk'),
 dict(id='bs-what', topic='Bacterial spot', title='What is bacterial spot',
  text='Bacterial spot is caused by bacteria of the Xanthomonas genus. It produces small dark water soaked spots on leaves that turn brown to black and are often ringed by a yellow halo. On fruit it forms raised scabby lesions that make the produce unmarketable. Because the cause is bacterial rather than fungal, ordinary fungicides do not cure it.',
  tags='bacterial spot xanthomonas water soaked spots scabby fruit lesions bacteria not fungus'),
 dict(id='bs-treat', topic='Bacterial spot', title='How to treat bacterial spot',
  text='Copper based sprays slow the spread of bacterial spot but do not cure infected tissue. Remove severely infected plants to reduce the amount of bacteria present. Never work among plants while the foliage is wet because bacteria spread readily by contact and on tools. Sanitise stakes, ties and pruning tools between plants.',
  tags='bacterial spot treatment copper spray sanitise tools remove plants wet foliage contact spread'),
 dict(id='healthy', topic='Healthy leaves', title='What a healthy tomato leaf looks like',
  text='A healthy tomato leaf is uniformly medium to dark green with firm turgid tissue and no spotting, yellowing, curling or necrotic margins. Veins are evenly coloured and the underside is free of mould, webbing or insect eggs. Mild cupping in strong heat can be normal and is not a disease symptom.',
  tags='healthy leaf normal appearance green turgid no spots what should look like'),
]
