DOCS = [
 dict(id='yellow', topic='Leaf symptoms', title='Why are my leaves turning yellow',
  text='Yellowing of leaves, known as chlorosis, has several causes. Uniform yellowing of the oldest lower leaves usually indicates nitrogen deficiency because nitrogen is mobile and the plant moves it to new growth. Yellowing between the veins while veins stay green suggests magnesium or iron deficiency. Yellowing combined with wilting often means overwatering and root suffocation. Yellowing with dark spots points to disease rather than nutrition.',
  tags='yellow leaves chlorosis nitrogen deficiency magnesium iron overwatering causes why yellowing'),
 dict(id='nitrogen', topic='Nutrition', title='Nitrogen deficiency in crops',
  text='Nitrogen deficiency appears first on older lower leaves as a uniform pale green to yellow colour, with stunted growth and thin stems. Nitrogen is mobile within the plant so it is relocated from old tissue to new shoots. Correct it with a balanced nitrogen fertiliser or well rotted manure. Excess nitrogen produces lush leafy growth with poor fruit set and increases susceptibility to disease.',
  tags='nitrogen deficiency pale older leaves stunted fertiliser manure mobile nutrient excess nitrogen'),
 dict(id='potassium', topic='Nutrition', title='Potassium and phosphorus deficiency',
  text='Potassium deficiency shows as scorching and browning along leaf margins of older leaves, with weak stems and uneven fruit ripening. Phosphorus deficiency produces dark green to purple tinted leaves, especially on the underside, together with poor root development and delayed flowering. Phosphorus uptake is reduced in cold soil even when the nutrient is present.',
  tags='potassium deficiency leaf margin scorch phosphorus purple leaves roots flowering cold soil'),
 dict(id='magnesium', topic='Nutrition', title='Magnesium and iron deficiency',
  text='Magnesium deficiency causes interveinal chlorosis on older leaves, meaning the tissue between veins turns yellow while the veins remain green. Iron deficiency causes the same interveinal pattern but appears on the youngest leaves first because iron is immobile. Magnesium can be corrected with epsom salt applied to soil or as a foliar spray. Iron deficiency is often caused by high soil pH rather than absence of iron.',
  tags='magnesium iron deficiency interveinal chlorosis epsom salt soil ph young old leaves immobile'),
 dict(id='curl', topic='Leaf symptoms', title='Why are my leaves curling',
  text='Leaf curl has both harmless and serious causes. Upward curling in hot dry weather is a normal water conservation response and resolves in the evening. Downward curling with thickened leathery texture can follow heavy pruning or excess nitrogen. Curling with mottled yellow patterns and stunted growth suggests a viral infection such as tomato yellow leaf curl virus, which is spread by whiteflies and cannot be cured. Curling with distorted new growth may indicate herbicide drift.',
  tags='leaf curl curling upward downward heat virus whitefly herbicide drift causes distorted'),
 dict(id='spots', topic='Leaf symptoms', title='How to tell disease types apart from leaf spots',
  text='Concentric rings inside a brown spot indicate early blight. Large greasy irregular blotches with white fuzz underneath indicate late blight. Many small dark water soaked spots with yellow halos indicate bacterial spot. Small circular spots with grey centres and dark borders indicate septoria leaf spot. Yellow patches on the upper surface with fuzzy growth beneath indicate downy mildew. A hand lens greatly improves field diagnosis.',
  tags='identify leaf spots difference between diseases diagnosis compare septoria downy mildew rings halos'),
 dict(id='water', topic='Crop care', title='How to water tomato plants correctly',
  text='Water deeply and less frequently rather than shallow daily watering, so that roots grow downward. Apply water at the soil line using drip irrigation or a soaker hose rather than overhead sprinklers, because wet foliage is the single largest driver of fungal and bacterial disease. Water early in the morning so that any splashed foliage dries within the hour. Inconsistent watering causes blossom end rot and fruit cracking.',
  tags='watering tomato irrigation drip soaker overhead morning blossom end rot cracking deep watering'),
 dict(id='soil', topic='Crop care', title='Soil and pH requirements for tomatoes',
  text='Tomatoes grow best in well drained loamy soil rich in organic matter with a pH between 6.0 and 6.8. Below pH 5.5 the availability of calcium and magnesium falls and aluminium toxicity becomes possible. Above pH 7.5 iron, manganese and zinc become locked out, producing deficiency symptoms despite adequate soil content. Lime raises pH and elemental sulphur lowers it, but both act slowly over months.',
  tags='soil ph tomato requirements loam organic matter lime sulphur nutrient lockout drainage'),
 dict(id='rotation', topic='Crop care', title='Why crop rotation matters',
  text='Many pathogens survive in soil and crop debris between seasons. Planting the same family in the same ground repeatedly allows populations of those pathogens to build up. Tomato, potato, pepper, eggplant and tobacco all belong to the solanaceae family and share diseases, so they must not follow one another. A gap of two to three seasons with unrelated crops such as legumes or cereals breaks the disease cycle and improves soil structure.',
  tags='crop rotation solanaceae family tomato potato pepper eggplant pathogen buildup soil disease cycle'),
 dict(id='mulch', topic='Crop care', title='Benefits of mulching',
  text='Mulch forms a physical barrier that stops rain and irrigation from splashing soil borne spores onto lower leaves, which is the main infection route for early blight and septoria. It also conserves soil moisture, evens out soil temperature and suppresses weeds. Straw, dried grass clippings and black plastic all work. Keep mulch a few centimetres clear of the stem to avoid rot.',
  tags='mulch mulching straw plastic splash spores soil moisture weeds benefits how to'),
]
