# Query augmentation: natural phrasings a user is likely to type for each passage.
# Indexed alongside the passage so retrieval matches question wording, not just topic wording.
QUERIES = {
 'eb-what': 'what is early blight, early blight symptoms, brown spots with rings on tomato leaves, target spots on leaves',
 'eb-treat': 'how do i treat early blight, early blight cure, spray for early blight, stop early blight spreading',
 'eb-prevent': 'how to prevent early blight, avoid early blight next season, stop early blight coming back',
 'lb-what': 'what is late blight, late blight symptoms, greasy brown patches on leaves, white mould under leaves',
 'lb-treat': 'how do i treat late blight, late blight cure, save my plants from late blight, late blight spray',
 'lb-conditions': 'when does late blight happen, weather for late blight, late blight risk conditions, humidity late blight',
 'bs-what': 'what is bacterial spot, small black spots on tomato leaves, water soaked spots, scabby fruit',
 'bs-treat': 'how do i treat bacterial spot, bacterial spot cure, copper spray bacterial spot',
 'healthy': 'what does a healthy leaf look like, normal tomato leaf, is my leaf healthy',
 'yellow': 'why are my leaves yellow, leaves yellow, yellow leaves, leaves turning yellow, yellowing leaves, my plant is yellow, leaf discoloration yellow',
 'nitrogen': 'nitrogen deficiency, plant looks pale, stunted growth pale leaves, need fertiliser',
 'potassium': 'potassium deficiency, brown leaf edges, burnt leaf margins, phosphorus deficiency, purple leaves',
 'magnesium': 'magnesium deficiency, iron deficiency, yellow between veins, green veins yellow leaf, interveinal',
 'curl': 'why are my leaves curling, leaves curling up, curled leaves, leaf curl, twisted leaves',
 'spots': 'what are these spots on my leaves, how to identify leaf disease, tell diseases apart, spots on leaves meaning, diagnose my leaf',
 'water': 'how often should i water tomatoes, watering tomatoes, best way to water, overwatering tomatoes',
 'soil': 'what soil do tomatoes need, best ph for tomatoes, soil ph, soil requirements tomato',
 'rotation': 'what is crop rotation, why rotate crops, where to plant tomatoes next year, same soil again',
 'mulch': 'should i mulch, what is mulching for, benefits of mulch, straw around plants',
 'aphid': 'aphids, tiny green insects on my plants, sticky leaves bugs, greenfly, sap sucking insects',
 'whitefly': 'whiteflies, small white flies on leaves, white insects fly up, virus spread by insects',
 'hornworm': 'caterpillar eating my leaves, big green caterpillar, hornworm, something is eating my plant',
 'fungicide': 'is fungicide safe, how long before harvest after spraying, fungicide resistance, protective equipment spraying',
 'organic': 'organic disease control, natural remedies for plant disease, no chemicals, organic spray options',
 'leafstruct': 'how does a leaf work, parts of a leaf, leaf structure, stomata, what is inside a leaf',
 'photosyn': 'what is photosynthesis, why does disease reduce yield, how do plants make food, chlorophyll',
 'humidity': 'does humidity cause disease, why do wet leaves get sick, leaf wetness, morning dew disease',
 'harvest': 'when to pick tomatoes, how to store tomatoes, should i refrigerate tomatoes, ripening',
 'spacing': 'how far apart to plant tomatoes, plant spacing, should i stake tomatoes, pruning lower leaves',
 'scope': 'what can this system detect, how accurate is this model, what diseases does this find, limitations of this tool, can it detect other crops',
}
